import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import fs from "fs";
import { PROMPT_PATH, get_prompts } from "@/utils/utils";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const prompts = get_prompts();
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="basis-1/4 p-4">
            <Link className="block" href="/">
              notes dashboard v1
            </Link>
            {prompts.map((prompt) => {
              return (
                <Link className="block" href={`/${prompt.name}`}>
                  {prompt.name}
                </Link>
              );
            })}
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
